if (HDEEM_LIBRARIES_DIRS AND HDEEM_INCLUDE_DIRS)
    set (Hdeem_FIND_QUIETLY TRUE)
endif (HDEEM_LIBRARIES_DIRS AND HDEEM_INCLUDE_DIRS)

find_path(HDEEM_INCLUDE_DIRS NAMES hdeem.h HINTS ${HDEEM_INCLUDE_DIRS} ENV CPATH C_INCLUDE_PATH)
message(WARNING "HDEEM_INCLUDE_DIRS " ${HDEEM_INCLUDE_DIRS})
find_library(HDEEM_LIBRARIES NAMES hdeem HINTS ${HDEEM_LIBRARIES_DIRS} ENV LIBRARY_PATH LD_LIBRARY_PATH)
message(WARNING "HDEEM_LIBRARIES " ${HDEEM_LIBRARIES})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HDEEM DEFAULT_MSG HDEEM_LIBRARIES HDEEM_INCLUDE_DIRS)

set(HDEEM_LIBRARIES "${HDEEM_LIBRARIES};rt;freeipmi")

mark_as_advanced(HDEEM_INCLUDE_DIRS HDEEM_LIBRARIES)
