if (FreeIPMI_INCLUDE_DIRS AND FreeIPMI_LIBRARIES)
    set (FreeIPMI_FIND_QUIETLY TRUE)
endif()

find_path(FreeIPMI_INCLUDE_DIRS NAMES freeipmi/freeipmi.h HINTS ${FreeIPMI_INCLUDE_DIRS} ${FreeIPMI_ROOT_DIR}/include ENV CPATH C_INCLUDE_PATH)
find_library(FreeIPMI_LIBRARIES NAMES freeipmi HINTS ${FreeIPMI_LIBRARIES_DIRS} ${FreeIPMI_ROOT_DIR}/lib ENV LIBRARY_PATH LD_LIBRARY_PATH)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FreeIPMI DEFAULT_MSG FreeIPMI_LIBRARIES FreeIPMI_INCLUDE_DIRS)

if(FreeIPMI_FOUND)
	add_library(FreeIPMI::FreeIPMI UNKNOWN IMPORTED GLOBAL)
	set_target_properties(FreeIPMI::FreeIPMI PROPERTIES
		IMPORTED_LINK_INTERFACE_LANGUAGES "C"
		IMPORTED_LOCATION "${FreeIPMI_LIBRARIES}"
        INTERFACE_INCLUDE_DIRECTORIES "${FreeIPMI_INCLUDE_DIRS}"
	)

	mark_as_advanced(FreeIPMI_INCLUDE_DIRS FreeIPMI_LIBRARY)
endif()
